config/routes.rb
Pitchcard::Application.routes.draw do

  root :to => "home#index"

  devise_for :users

  resources :discover, only: :index
  
  resources :pitches, except: [:new, :show]
  get '/new', to: 'pitches#new'

  get '/:username', to: 'profiles#show', as: 'profile'
  get '/:username/:pitch_id', to: 'pitches#show', as: 'profile_pitch'

  post '/:username/:pitch_id/comments', to: 'comments#create', as: 'profile_pitch_comments'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :pitch
  belongs_to :user
  has_many :children, class_name: 'Comment'
  belongs_to :parent, class_name: 'Comment'

  def children
    Comment.where(parent_id: id)
  end
end

app/models/pitch.rb
class Pitch < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  mount_uploader :image, ImageUploader

  def root_comments
    Comment.where(pitch_id: id, parent_id: nil)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pitches

  attr_accessor :login

  validates :username, :uniqueness => { :case_sensitive => false }

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

  def name_or_username
    self.name or self.username
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
      devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
      devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :name, :url, :location, :email, :password, :password_confirmation, :current_password) }
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_action :set_user, :set_pitch

  def create
    @comment = @pitch.comments.build(comment_params)
    @comment.user_id = current_user.id

    respond_to do |format|
      if @comment.save

        format.json { render json: @comment.to_json(:include => [{ :user => { :methods => :name_or_username, :only => :name_or_username } }, { :pitch => { :only => [:id, :user], :include => {:user => { :only => :username } } } }]), status: :created, location: @pitch }
        # format.html { redirect_to profile_pitch_path(@pitch.user.username, @pitch.id) }
      else
        format.json { render json: @comment.errors, status: :unprocessable_entity }
        # format.html { render action: 'show' }
      end
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :parent_id)
  end

  def set_user
    @user = User.find_by username: params[:username]
  end

  def set_pitch
    @pitch = @user.pitches.find(params[:pitch_id])
  end
end

app/controllers/discover_controller.rb
class DiscoverController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/pitches_controller.rb
class PitchesController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_action :set_user, only: [:show]

  def index
  end

  def show
    @pitch = @user.pitches.find(params[:pitch_id])
  end

  def new
  end

  def create
    @pitch = current_user.pitches.build(pitch_params)

    respond_to do |format|
      if @pitch.save
        format.html { redirect_to profile_pitch_path(current_user.username, @pitch.id) }
      else
        format.html { render action: 'new' }
      end
    end
  end

  private

  def pitch_params
    params.require(:pitch).permit(:title, :problem, :solution, :difference, :image)
  end

  def set_user
    @user = User.find_by username: params[:username]
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user

  def show
  end

  private

  def set_user
    @user = User.find_by username: params[:username]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/discover_helper.rb
module DiscoverHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pitches_helper.rb
module PitchesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/discover/index.html.erb
<%= render partial: 'shared/header', locals: { title: 'Discover', description: 'Lorem ipsum dolor sit amet.', label: '' } %>

app/views/home/index.html.erb
<%= render partial: 'shared/header', locals: { title: 'Pitchcard', description: 'Pitch your ideas and get feedback.', label: '' } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pitchcard</title>
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

  <header class="navbar pc-nav">
    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#bs-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Pitchcard</a>
    </div>

    <nav class="collapse navbar-collapse" id="bs-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <a href="/discover">Discover</a>
        </li>
        <li>
          <a href="/new">New</a>
        </li>
      </ul>

      <% if user_signed_in? %>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <a href="/<%= current_user.username %>"><%= current_user.name ? current_user.name : current_user.username %></a>
        </li>
      </ul>
      <% end %>
    </nav>
  </header>

  <% if notice %>
  <div class="pc-flash notice bg-info">
    <div class="container">
      <p><%= notice %>
    </div>
  </div>
  <% end %>

  <% if alert %>
  <div class="pc-flash alert bg-danger">
    <div class="container">
      <p><%= alert %>
    </div>
  </div>
  <% end %>

  <%= yield %>

  <footer class="pc-footer">
    <div class="container">
      Made with ♥ in Manchester by <a href="http://twitter.com/acason" target="_blank">Alex Cason</a>
    </div>
  </footer>

</body>
</html>

app/views/pitches/index.html.erb
<div class="page-header">
  <h1>Pitches</h1>
</div>

app/views/pitches/new.html.erb
<%= form_for :pitch, url: pitches_path do |f| %>
  <div class="pc-pitch-header">
    <span class="btn btn-default btn-file">
      Choose cover image <%= f.file_field :image, accept: 'image/*' %>
    </span>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-md-10 col-md-offset-1">

        <div class="pc-pitch-container">

          <div class="pc-pitch-title-container">
            <%= f.text_area :title, rows: 1, class: 'form-control pc-new-pitch-title', autocomplete: 'off', autofocus: true, value: 'YOUR PITCH TITLE' %>
          
            <p class="pc-pitch-author">by <%= current_user.name_or_username %></p>
          </div>

          <div class="pc-pitch-problem">
            <header>
              <h2>The Problem</h2>
            </header>

            <div id="pitchProblem" class="editable" data-placeholder="Describe the problem" data-input="pitch_problem"></div>

            <%= f.text_area :problem, class: 'hidden' %>
          </div>
              
          <div class="pc-pitch-solution">
            <header>
              <h2>My Solution</h2>
            </header>

            <div id="pitchSolution" class="editable" data-placeholder="Outline your solution" data-input="pitch_solution"></div>

            <%= f.text_area :solution, class: 'hidden' %>
          </div>
   
          <div class="pc-pitch-submit">
            <%= f.button 'Create your pitch', class: 'btn btn-default' %>
          </div>

        </div>

      </div>
    </div>
  </div>

<% end %>

app/views/pitches/show.html.erb
<% if @pitch.image %>
<div class="pc-pitch-header pc-image-set" style="background-image: url(<%= @pitch.image.url %>)"></div>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">

      <div class="pc-pitch-container">

        <div class="pc-pitch-title-container">
          <h1 class="pc-pitch-title"><%= @pitch.title %></h1>

          <p class="pc-pitch-author">by <%= @pitch.user.name_or_username %></p>
        </div>

        <div class="pc-pitch-problem">
          <header>
            <h2>The Problem</h2>
          </header>

          <%= @pitch.problem.html_safe %>
        </div>

        <div class="pc-pitch-solution">
          <header>
            <h2>My Solution</h2>
          </header>

          <%= @pitch.solution.html_safe %>
        </div>

        <div class="pc-pitch-comments-container">
          <%= form_for :comment, url: profile_pitch_comments_path, remote: true, html: { class: 'pc-pitch-comment-form' } do |f| %>

            <div class="form-group">
              <%= f.text_area :body, rows: 4, class: 'form-control', placeholder: 'Write a comment...' %>
            </div>

            <div class="text-right">
              <%= f.button 'Submit', class: 'btn btn-default' %>
            </div>

          <% end %>

          <%# if @pitch.root_comments.length > 0 %>
            <ul class="pc-pitch-comments pc-pitch-comments-top">
              <% @pitch.root_comments.each do |comment| %>
              <li class="pc-pitch-comment-top">
                <header>
                  <h1><%= comment.user.name_or_username %></h1>
                </header>

                <p><%= simple_format(comment.body) %></p>

                <div class="row pc-pitch-comment-details">
                  <div class="col-xs-6">
                    <span class="text-muted"><%= time_ago_in_words(comment.created_at) %> ago</span>
                  </div>

                  <div class="col-xs-6 text-right">
                    <a href="#" class="pc-pitch-comment-reply">Reply</a>
                  </div>
                </div>

                <div class="pc-pitch-comment-replies">
                  <%# if comment.children.length > 0 %>
                  <ul class="pc-pitch-comments">
                    <% comment.children.each do |reply| %>
                    <li>
                      <header>
                        <h1><%= reply.user.name_or_username %></h1>
                      </header>

                      <p><%= simple_format(reply.body) %></p>

                      <div class="row pc-pitch-comment-details">
                        <div class="col-xs-6">
                          <span class="text-muted"><%= time_ago_in_words(reply.created_at) %> ago</span>
                        </div>

                        <div class="col-xs-6 text-right">
                          <a href="#" class="pc-pitch-comment-reply">Reply</a>
                        </div>
                      </div>
                    </li>
                    <% end %>
                  </ul>
                  <%# end %>

                  <%= form_for :comment, url: profile_pitch_comments_path, remote: true, html: { class: 'pc-pitch-comment-reply-form', style: 'display: none;' } do |f| %>
                    <%= f.hidden_field :parent_id, value: comment.id %>

                    <div class="form-group">
                      <%= f.text_area :body, rows: 4, class: 'form-control', placeholder: 'Write a comment...' %>
                    </div>

                    <div class="text-right">
                      <%= f.button 'Submit', class: 'btn btn-default' %>
                    </div>

                  <% end %>
                </div>
              </li>
              <% end %>
            </ul>
          <%# end %>
        </div>

      </div>

    </div>

  </div>
</div>

app/views/profiles/show.html.erb
<%= render partial: 'shared/header', locals: { title: @user.name_or_username, description: 'Lorem ipsum dolor sit amet.', label: '' } %>

<div class="container">
  <% if @user.pitches.length > 0 %>
  <ul>
    <% @user.pitches.each do |pitch| %>
    <li>
      <a href="/<%= @user.username %>/<%= pitch.id.to_s %>"><%= pitch.title %></a>
    </li>
    <% end %>
  </ul>
  <% end %>
</div>

app/views/shared/_header.html.erb
<div class="pc-header">
  <div class="container">
    <h1>
      <%= title %>
    </h1>

    <% if description %>
    <p>
      <%= description %>

      <% if label %>
      <span class="label label-default"><%= label %></span>
      <% end %>
    </p>
    <% end %>
  </div>
</div>